[tool.poetry]
name = "jnp-3r.net"
version = "0.1.0"
description = ""
authors = ["Juniper S. <wildcat8088@live.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
